API.h
LODWORD
Referenced by Find, MoveCaret, PaintWindow, UserMessageProc, WndProc.
HIDWORD
Referenced by Find, MoveCaret, PaintWindow, UserMessageProc, WndProc.
UM_UP
Referenced by UserMessageProc.
UM_DOWN
Referenced by UserMessageProc.
UM_LEFT
Referenced by UserMessageProc.
UM_RIGHT
Referenced by UserMessageProc.
UM_RETURN
Referenced by UserMessageProc, WndProc.
UM_END
Referenced by UserMessageProc.
UM_CHAR
Referenced by UserMessageProc, WndProc.
UM_TEXT
Referenced by PaintWindow, UserMessageProc.
UM_DELETE
Referenced by UserMessageProc, WndProc.
UM_CURSOR
Referenced by UserMessageProc, WndProc.
UM_CHOOSE
Referenced by UserMessageProc, WndProc.
UM_HOME
Referenced by UserMessageProc.
UM_NEW
Referenced by UserMessageProc, WndProc.
UM_OPEN
Referenced by UserMessageProc, WndProc.
UM_SAVE
Referenced by UserMessageProc, WndProc.
UM_CLOSE
Referenced by UserMessageProc, WndProc.
UM_ALL
Referenced by UserMessageProc, WndProc.
UM_COPY
Referenced by UserMessageProc, WndProc.
UM_PASTE
Referenced by UserMessageProc, WndProc.
UM_CANCEL
Referenced by UserMessageProc, WndProc.
UM_FIND
Referenced by Find, UserMessageProc.
UM_REPLACE
Referenced by Find.
UR_NOPATH
Referenced by UserMessageProc, WndProc.
UR_NOTSAVED
Referenced by UserMessageProc, WndProc.
UR_NOTCANCEL
Referenced by UserMessageProc.
UR_ERROR
Referenced by Find, MoveCaret, PaintWindow, UserMessageProc, WndProc.
UR_SUCCESS
Referenced by UserMessageProc, WndProc.
UR_SAVED
Referenced by UserMessageProc, WndProc.
FIND_COMPELTE
Referenced by Find.
FIND_LHCASE
Referenced by Find.
TEXT_SIZE
Referenced by CreateText, UserMessageProc.
TAB_SIZE
Referenced by UserMessageProc.
typedef CText* HTEXT
typedef ULONGLONG FPARAM
typedef ULONGLONG SPARAM
typedef ULONGLONG RVALUE
HTEXT _stdcall CreateText(int iCharWidth, int iCharHeight)
References Install::Height, Initialize_Cursor, CText::NewFile, pTChar, TEXT_SIZE, Install::Width.
Referenced by CreateKernel.
BOOL _stdcall DestroyText(HTEXT &hText)
References Free_Buffer, pBuffer, pCursor, pRecord, pTChar.
RVALUE _stdcall UserMessageProc(HTEXT hText, int x, int y, UINT message, FPARAM fParam, SPARAM sParam)
References Record::ACT, Alloc_Buffer, CText::BackSpace, Cursor::Characters_before_Cursor, Cursor::CharactersProperty_before_Cursor, Cursor::Choose, CText::ClearAll, CText::Copy, Cursor::CursorLocation, Cursor::CursorToPosition, Cursor::CursorToPosition_After, CText::Delete, Record::end, Cursor::end, CText::End_Position, CText::EnterNewLine, CText::FilePath, CText::First_Position, CText::GetLinePointer, Install::Height, HIDWORD, CText::Insert, Cursor::isChoose, Cursor::isEnAfter, Cursor::isLegalCursor, CText::isSaved, CText::Line_Number, CText::Line_Size, CText::Line_Width, Position::LineNumber, LODWORD, CText::Max_Line_Width, MaxBufferSize, CText::NewFile, pBuffer, Cursor::PositionToCursor, pTChar, RD_DELETE, RD_INSERT, RD_MERGE_LINE, RD_RETURN, CText::ReadText, Record::ReDo, Cursor::ResetChoose, CText::Save, Record::Save_Delete_Data, Record::Save_Merge_Line_Data, CText::SeekStrings, Position::Sequence, Record::Set_Choose_Data, Set_Height_Light, Cursor::SethText, Record::start, Cursor::start, StringToWString, TAB_SIZE, TEXT_SIZE, CLine::TransformToWString, UM_ALL, UM_CANCEL, UM_CHAR, UM_CHOOSE, UM_CLOSE, UM_COPY, UM_CURSOR, UM_DELETE, UM_DOWN, UM_END, UM_FIND, UM_HOME, UM_LEFT, UM_NEW, UM_OPEN, UM_PASTE, UM_RETURN, UM_RIGHT, UM_SAVE, UM_TEXT, UM_UP, UR_ERROR, UR_NOPATH, UR_NOTCANCEL, UR_NOTSAVED, UR_SAVED, UR_SUCCESS, wchTostring, Install::Width, WStringToWch.
Referenced by Find, MoveCaret, PaintWindow, WndProc.
Cursor* Initialize_Cursor(CText *p, int Width, int Height)
References pCursor.
Referenced by CreateText.
void Alloc_Buffer(wchar_t *&p, size_t &Old_Size, size_t New_Size)
Referenced by UserMessageProc.
void Free_Buffer(wchar_t *&p)
Referenced by DestroyText.
void Set_Height_Light(int LineNumber, Position ps, Position pe, short int &start, short int &end)
References Cursor::end, Position::LineNumber, Position::Sequence, Cursor::start.
Referenced by UserMessageProc.