CText.h
UNICODE
int* GetNextValArray(std::wstring SubStr)
Referenced by CText::SeekStrings.
size_t NumberOfZH(const std::wstring &wstr)
Referenced by WStringToString.
std::wstring StringToWString(const std::string &s)
Referenced by CText::ReadText, UserMessageProc.
std::string WStringToString(const std::wstring &ws)
References NumberOfZH.
Referenced by CText::Save, wchTostring.
std::string wchTostring(TCHAR *pwch)
References WStringToString.
Referenced by UserMessageProc.
void WStringToWch(const std::wstring &ws, TCHAR *&pwch)
Referenced by UserMessageProc.
std::queue<std::wstring> WStrToLineWStr(std::wstring WSTR)
Referenced by CText::Insert.