EditBox.cpp
MAX_LOADSTRING
Referenced by Find, wWinMain.
HINSTANCE hInst
Referenced by InitInstance, WndProc.
WCHAR szTitle[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, wWinMain.
WCHAR szWindowClass[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, MyRegisterClass, wWinMain.
HTEXTINFO hTextInfo
Referenced by ReleaseTextInfo.
WCHAR szFindWhat[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by Find, WndProc.
WCHAR szReplaceWhat[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by Find, WndProc.
ULONGLONG uiFindMode
Referenced by Find, WndProc.
ATOM MyRegisterClass(HINSTANCE hInstance)
References IDC_EDITBOX, IDI_EDITBOX, IDI_SMALL, szWindowClass, WndProc.
Referenced by wWinMain.
BOOL InitInstance(HINSTANCE, int)
References hInst, szTitle, szWindowClass.
Referenced by wWinMain.
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM)
References About, AdjustCaretPosBeforeBackspace, AdjustWindowPos, CARETPOS, CARETSIZE, CHARSIZE, chDEBUGMESSAGEBOX, CreateTextInfo, CreateTimer, DefaultFill, ENDPOS, Find, FIND, HIDWORD, hInst, HTEXT, IDD_ABOUTBOX, IDD_FINDDIALOG, IDM_ABOUT, IDM_ALL, IDM_CANCEL, IDM_COPY, IDM_CUT, IDM_EXIT, IDM_FIND, IDM_NEW, IDM_OPEN, IDM_PASTE, IDM_REPLACE, IDM_SAVE, IDM_SAVEAS, INRANGEX, INRANGEY, IsTimerStopped, KillTimer, LODWORD, MEMDC, MoveCaret, MTIMER, MyInvalidateRect, MyScrollWindow, PAGESIZE, PaintWindow, pCursor, ReleaseTextInfo, REPLACE, SelectCaretPos, SelectHighlight, SelectTextSize, SelectTitledWindow, SelectUntitledWindow, SelectWindowPos, SelectWindowSize, STARTPOS, szFindWhat, szReplaceWhat, TEXTSIZE, uiFindMode, UM_ALL, UM_CANCEL, UM_CHAR, UM_CHOOSE, UM_CLOSE, UM_COPY, UM_CURSOR, UM_DELETE, UM_NEW, UM_OPEN, UM_PASTE, UM_RETURN, UM_SAVE, UR_ERROR, UR_NOPATH, UR_NOTSAVED, UR_SAVED, UR_SUCCESS, UserMessageProc, USHEIGHT, USWIDTH, WINDOWPOS, WINDOWSIZE.
Referenced by MyRegisterClass.
INT_PTR CALLBACK About(HWND, UINT, WPARAM, LPARAM)
Referenced by WndProc.
INT_PTR CALLBACK Find(HWND, UINT, WPARAM, LPARAM)
References AdjustWindowPos, AFTER_CARET, BEFORE_CARET, CARETPOS, FIND, FIND_COMPELTE, FIND_LHCASE, HIDWORD, HTEXT, IDC_COMPLETEMATCH, IDC_FINDWHAT, IDC_LHCASE, IDC_REPLACEWHAT, IDC_TYPEHINT, LODWORD, _TEXT_INFO::m_hWnd, MAX_LOADSTRING, REPLACE, SelectCaretPos, SelectHighlight, SelectTextSize, szFindWhat, szReplaceWhat, TEXTSIZE, uiFindMode, UM_FIND, UM_REPLACE, UR_ERROR, UserMessageProc, WHOLE_TEXT.
Referenced by WndProc.
int APIENTRY wWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPWSTR lpCmdLine, _In_ int nCmdShow)
References IDC_EDITBOX, IDS_APP_TITLE, InitInstance, MAX_LOADSTRING, MyRegisterClass, szTitle, szWindowClass.