CText
friend class Text_iterator
friend class Cursor
friend struct Record
CLine* CText::pFirstLineHead
Referenced by BackSpace, ClearAll, CText, DeleteLines, First_Position, GetLinePointer, InsertLine, Max_Line_Width, NewFile, ReadText, Save, ShowText.
int CText::nLineNumbers
Referenced by ClearAll, CText, DeleteLines, End_Position, Line_Number, NewFile, ReadText, UpDataLineNumber.
std::string CText::FileName
Referenced by ClearAll, CText, FilePath, NewFile, ReadText, Save.
bool CText::bSave
Referenced by BackSpace, ClearAll, Delete, DeleteLines, EnterNewLine, Insert, isSaved, NewFile, ReadText, Save.
CText::CText()
References FileName, nLineNumbers, pFirstLineHead.
CText::~CText()
References ClearAll.
void CText::NewFile()
References bSave, ClearAll, FileName, nLineNumbers, pFirstLineHead.
Referenced by CreateText, UserMessageProc.
void CText::ReadText(std::string filename)
References bSave, ClearAll, CLine::CreateLine, FileName, nLineNumbers, pFirstLineHead, CLine::pNextLine, StringToWString.
Referenced by UserMessageProc.
void CText::Save(std::string filename="", bool isChange=false)
References bSave, FileName, CLine::nDataSize, pFirstLineHead, CLine::pNextLine, CLine::TransformToWString, WStringToString.
Referenced by UserMessageProc.
void CText::ClearAll()
References bSave, FileName, nLineNumbers, pFirstLineHead, CLine::pNextLine.
Referenced by DeleteLines, NewFile, ReadText, UserMessageProc, ~CText.
void CText::ShowText() const
References pFirstLineHead, CLine::pNextLine, CLine::ShowLineData.
void CText::DeleteLines(int first, int last)
References bSave, ClearAll, GetLinePointer, CLine::nLineNumber, nLineNumbers, pFirstLineHead, CLine::pNextLine, UpDataLineNumber.
Referenced by BackSpace, Delete, Record::ReDo.
Position CText::Delete(Position first, Position last)
References bSave, CLine::DeleteLine, DeleteLines, GetLinePointer, CLine::InsertStrings, Position::LineNumber, CLine::nDataSize, CLine::nLineNumber, CLine::pNextLine, Position::Sequence, CLine::TransformToWString.
Referenced by Record::ReDo, Replace, UserMessageProc.
Position CText::BackSpace(Position position)
References CLine::BackSpace, bSave, DeleteLines, CLine::InsertStrings, Position::LineNumber, CLine::nDataSize, CLine::nLineNumber, pFirstLineHead, CLine::pNextLine, Position::Sequence, CLine::TransformToWString.
Referenced by UserMessageProc.
Position CText::Insert(Position start, std::wstring String)
References bSave, EnterNewLine, GetLinePointer, CLine::InsertStrings, Position::LineNumber, CLine::pNextLine, Position::Sequence, WStrToLineWStr.
Referenced by Record::ReDo, Replace, UserMessageProc.
std::wstring CText::Copy(Position start, Position end)
References GetLinePointer, Position::LineNumber, CLine::nDataSize, CLine::nLineNumber, CLine::pNextLine, Position::Sequence, CLine::TransformToWString.
Referenced by Record::Save_Delete_Data, UserMessageProc.
Position CText::EnterNewLine(Position position)
References CLine::bBlankLine, bSave, CLine::CreateLine, CLine::DeleteLine, GetLinePointer, InsertLine, Position::LineNumber, CLine::nDataSize, CLine::pNextLine, Position::Sequence, CLine::TransformToWString.
Referenced by Insert, Record::ReDo, UserMessageProc.
bool CText::SeekStrings(std::wstring Str, Position &start, Position &end)
References Text_iterator::GetCurPositin, GetNextValArray, Text_iterator::GoEnd, Text_iterator::GoPosition.
Referenced by UserMessageProc.
Position CText::Replace(Position start, Position end, std::wstring Str)
References Delete, Insert, Position::Sequence.
bool CText::isSaved()
References bSave.
Referenced by UserMessageProc.
std::string CText::FilePath()
References FileName.
Referenced by UserMessageProc.
int CText::Line_Size(int LineNumber)
References GetLinePointer, CLine::nDataSize.
Referenced by Cursor::isEnAfter, UserMessageProc.
int CText::Line_Width(int LineNumber, int Width, int end=0)
References GetLinePointer, CLine::Line_Width.
Referenced by Cursor::CursorLocation, Cursor::PositionToCursor, UserMessageProc.
int CText::Max_Line_Width(int Width)
References CLine::Line_Width, pFirstLineHead, CLine::pNextLine.
Referenced by UserMessageProc.
int CText::Line_Number() const
References nLineNumbers.
Referenced by Cursor::CursorToPosition_After, GetLinePointer, Text_iterator::GoEnd, Text_iterator::isEnd, Cursor::isTextTail, Text_iterator::operator++, Text_iterator::Text_iterator, UserMessageProc.
CLine * CText::GetLinePointer(int LineNumber)
References Line_Number, CLine::nLineNumber, pFirstLineHead, CLine::pNextLine.
Referenced by Cursor::Characters_before_Cursor, Cursor::CharactersProperty_before_Cursor, Copy, Cursor::CursorToPosition_After, Delete, DeleteLines, End_Position, EnterNewLine, Text_iterator::GoEnd, Text_iterator::GoPosition, Insert, Cursor::isEnAfter, Text_iterator::isEnd, Cursor::isLegalCursor, Cursor::isTextTail, Line_Size, Line_Width, Text_iterator::operator--, Record::ReDo, Record::Save_Merge_Line_Data, Text_iterator::Text_iterator, UserMessageProc.
Position CText::First_Position()
References pFirstLineHead.
Referenced by UserMessageProc.
Position CText::End_Position()
References GetLinePointer, CLine::nDataSize, nLineNumbers.
Referenced by UserMessageProc.
void CText::UpDataLineNumber(CLine *p, int Start)
References nLineNumbers, CLine::pNextLine, CLine::SetLineNumber.
Referenced by DeleteLines, InsertLine.
void CText::InsertLine(int AfterLineNumber)
References CLine::nLineNumber, pFirstLineHead, CLine::pNextLine, UpDataLineNumber.
Referenced by EnterNewLine.