CLine
friend class Line_iterator
Referenced by begin, DeleteLine, InsertStrings.
friend class CText
friend class Cursor
friend class Text_iterator
friend struct Record
CLine* CLine::pNextLine
Referenced by CText::BackSpace, CText::ClearAll, CLine, CText::Copy, Cursor::CursorToPosition_After, CText::Delete, CText::DeleteLines, CText::EnterNewLine, CText::GetLinePointer, CText::Insert, CText::InsertLine, InsertStrings, CText::Max_Line_Width, Text_iterator::operator++, operator=, CText::ReadText, Record::ReDo, CText::Save, CText::ShowText, CText::UpDataLineNumber, UpDataLineNumber, ~CLine.
DataBlock* CLine::pLineHead
Referenced by ClearLine, CLine, CreateLine, InsertStrings, Line_iterator::Line_iterator, Line_iterator::operator--, operator=, Line_iterator::Set, ShowLineData.
int CLine::nLineNumber
Referenced by CText::BackSpace, CLine, CText::Copy, Text_iterator::CurrentLineNumber, Cursor::CursorToPosition_After, CText::Delete, CText::DeleteLines, Text_iterator::GetCurPositin, CText::GetLinePointer, CText::InsertLine, InsertStrings, Text_iterator::isEnd, Cursor::isTextTail, Text_iterator::operator++, Text_iterator::operator--, operator=, SetLineNumber, ShowLineData, UpDataLineNumber.
int CLine::nDataSize
Referenced by CText::BackSpace, ClearLine, CLine, CText::Copy, CreateLine, Cursor::CursorToPosition_After, CText::Delete, DeleteLine, end, CText::End_Position, CText::EnterNewLine, Text_iterator::GoEnd, InsertStrings, Text_iterator::isEnd, Cursor::isTextTail, CText::Line_Size, Line_Width, Text_iterator::operator++, Text_iterator::operator--, Record::ReDo, CText::Save, Record::Save_Merge_Line_Data, size, TransformToWString.
int CLine::nBlocks
Referenced by ClearLine, CLine, CreateLine, DeleteSpareBlocks, InsertStrings.
bool CLine::bBlankLine
Referenced by ClearLine, CLine, CreateLine, DeleteLine, CText::EnterNewLine, InsertStrings, isBlankLine, Line_Width, TransformToWString.
CLine::CLine(int LNum, CLine *pNext=NULL)
References bBlankLine, nBlocks, nDataSize, nLineNumber, pLineHead, pNextLine.
Referenced by InsertStrings.
CLine::CLine(CLine &L)
References CreateLine, size, TransformToWString.
CLine::~CLine()
References ClearLine, pNextLine.
void CLine::CreateLine(std::wstring &String)
References bBlankLine, BLOCK_SIZE, ClearLine, nBlocks, nDataSize, pLineHead, DataBlock::pNextBlock, DataBlock::Strings.
Referenced by CLine, CText::EnterNewLine, InsertStrings, operator=, CText::ReadText.
void CLine::ClearLine()
References bBlankLine, nBlocks, nDataSize, pLineHead, DataBlock::pNextBlock.
Referenced by CreateLine, DeleteLine, InsertStrings, operator=, ~CLine.
void CLine::ShowLineData()
References nLineNumber, pLineHead, DataBlock::pNextBlock, DataBlock::Strings.
Referenced by CText::ShowText.
Line_iterator CLine::DeleteLine(int first, int last)
References bBlankLine, BLOCK_SIZE, ClearLine, copy, DeleteSpareBlocks, end, Line_iterator, nDataSize, Line_iterator::nIndex, Line_iterator::pBlock, DataBlock::pNextBlock.
Referenced by BackSpace, CText::Delete, CText::EnterNewLine, InsertStrings.
bool CLine::BackSpace(Position position)
References DeleteLine, Position::LineNumber, Position::Sequence.
Referenced by CText::BackSpace.
Line_iterator CLine::InsertStrings(int start, std::wstring String)
References bBlankLine, begin, BLOCK_SIZE, ClearLine, CLine, copy, CreateLine, DeleteLine, DeleteSpareBlocks, end, Line_iterator, nBlocks, nDataSize, Line_iterator::nIndex, nLineNumber, Line_iterator::pBlock, pLineHead, DataBlock::pNextBlock, pNextLine, TransformToWString, UpDataLineNumber.
Referenced by CText::BackSpace, CText::Delete, CText::Insert, Record::ReDo.
Line_iterator CLine::begin()
References Line_iterator.
Referenced by end, InsertStrings.
Line_iterator CLine::end()
References begin, nDataSize.
Referenced by DeleteLine, InsertStrings.
std::wstring CLine::TransformToWString(int first, int last)
References bBlankLine, nDataSize.
Referenced by CText::BackSpace, CLine, CText::Copy, CText::Delete, CText::EnterNewLine, InsertStrings, operator=, Record::ReDo, CText::Save, UserMessageProc.
size_t CLine::size() const
References nDataSize.
Referenced by CLine, operator=.
CLine & CLine::operator=(CLine &Line)
References ClearLine, CreateLine, nLineNumber, pLineHead, pNextLine, size, TransformToWString.
void CLine::SetLineNumber(int Number)
References nLineNumber.
Referenced by CText::UpDataLineNumber.
bool CLine::isBlankLine() const
References bBlankLine.
int CLine::Line_Width(int Width, int end=0)
References bBlankLine, nDataSize.
Referenced by Cursor::isLegalCursor, CText::Line_Width, CText::Max_Line_Width.
void CLine::DeleteSpareBlocks(DataBlock *p)
References nBlocks, DataBlock::pNextBlock.
Referenced by DeleteLine, InsertStrings.
void CLine::UpDataLineNumber()
References nLineNumber, pNextLine.
Referenced by InsertStrings.