Text_iterator
CText* Text_iterator::pText
Referenced by GoEnd, GoPosition, isEnd, operator++, operator--, Text_iterator, ~Text_iterator.
Line_iterator Text_iterator::currLine
Referenced by CurrentLineNumber, GetCurPositin, GoEnd, GoPosition, isEnd, operator!=, operator*, operator++, operator--, operator==, Text_iterator.
Text_iterator::Text_iterator()=default
Text_iterator::Text_iterator(CText &Text, int LineNumber=1, int position=1)
References currLine, CText::GetLinePointer, CText::Line_Number, pText, Line_iterator::Set.
Text_iterator::~Text_iterator()
References pText.
bool Text_iterator::isEnd()
References Line_iterator::CurrentPosition, currLine, CText::GetLinePointer, Line_iterator::GetLinePointer, CText::Line_Number, CLine::nDataSize, CLine::nLineNumber, pText.
void Text_iterator::GoPosition(Position position)
References currLine, CText::GetLinePointer, Position::LineNumber, pText, Position::Sequence, Line_iterator::Set.
Referenced by CText::SeekStrings.
void Text_iterator::GoEnd()
References currLine, CText::GetLinePointer, CText::Line_Number, CLine::nDataSize, pText, Line_iterator::Set.
Referenced by CText::SeekStrings.
Position Text_iterator::GetCurPositin()
References currLine, Line_iterator::nIndex, CLine::nLineNumber, Line_iterator::pLine.
Referenced by CText::SeekStrings.
int Text_iterator::CurrentLineNumber()
References currLine, CLine::nLineNumber, Line_iterator::pLine.
TCHAR Text_iterator::operator*()
References currLine, Line_iterator::isValid.
Text_iterator & Text_iterator::operator++()
References Line_iterator::CurrentPosition, currLine, Line_iterator::GetLinePointer, CText::Line_Number, CLine::nDataSize, CLine::nLineNumber, CLine::pNextLine, pText, Line_iterator::Set.
Text_iterator Text_iterator::operator++(int)
Text_iterator & Text_iterator::operator--()
References Line_iterator::CurrentPosition, currLine, CText::GetLinePointer, Line_iterator::GetLinePointer, CLine::nDataSize, CLine::nLineNumber, pText, Line_iterator::Set.
Text_iterator Text_iterator::operator--(int)
Text_iterator & Text_iterator::operator+(int n)
Text_iterator & Text_iterator::operator-(int n)
bool Text_iterator::operator==(const Text_iterator &Text)
References currLine.
bool Text_iterator::operator!=(const Text_iterator &Text)
References currLine.