Line_iterator
friend class CLine
friend class Text_iterator
CLine* Line_iterator::pLine
Referenced by Text_iterator::CurrentLineNumber, Text_iterator::GetCurPositin, GetLinePointer, Line_iterator, operator--, operator=, Set, ~Line_iterator.
TCHAR* Line_iterator::pWChar
Referenced by isValid, Line_iterator, operator*, operator+, operator++, operator--, operator=, Set, ~Line_iterator.
DataBlock* Line_iterator::pBlock
Referenced by CLine::DeleteLine, CLine::InsertStrings, Line_iterator, operator+, operator++, operator--, operator=, operator==, Set, ~Line_iterator.
int Line_iterator::nIndex
Referenced by CurrentPosition, CLine::DeleteLine, Text_iterator::GetCurPositin, CLine::InsertStrings, Line_iterator, operator+, operator++, operator--, operator=, operator==, Set.
Line_iterator::Line_iterator()=default
Line_iterator::Line_iterator(CLine &theLine, int index=1)
References nIndex, pBlock, pLine, CLine::pLineHead, pWChar, DataBlock::Strings.
Line_iterator::Line_iterator(const Line_iterator &m)
References nIndex, pBlock, pLine, pWChar.
Line_iterator::~Line_iterator()
References pBlock, pLine, pWChar.
void Line_iterator::Set(CLine &theLine, int index=1)
References nIndex, pBlock, pLine, CLine::pLineHead, pWChar, DataBlock::Strings.
Referenced by Text_iterator::GoEnd, Text_iterator::GoPosition, Text_iterator::operator++, Text_iterator::operator--, Text_iterator::Text_iterator.
int Line_iterator::CurrentPosition() const
References nIndex.
Referenced by Text_iterator::isEnd, Text_iterator::operator++, Text_iterator::operator--.
CLine * Line_iterator::GetLinePointer()
References pLine.
Referenced by Text_iterator::isEnd, Text_iterator::operator++, Text_iterator::operator--.
bool Line_iterator::isValid() const
References pWChar.
Referenced by Text_iterator::operator*.
Line_iterator & Line_iterator::operator++()
References BLOCK_SIZE, nIndex, pBlock, DataBlock::pNextBlock, pWChar, DataBlock::Strings.
Line_iterator Line_iterator::operator++(int)
Line_iterator & Line_iterator::operator--()
References BLOCK_SIZE, nIndex, pBlock, pLine, CLine::pLineHead, DataBlock::pNextBlock, pWChar, DataBlock::Strings.
Line_iterator Line_iterator::operator--(int)
Line_iterator & Line_iterator::operator+(int n)
References BLOCK_SIZE, nIndex, pBlock, DataBlock::pNextBlock, pWChar, DataBlock::Strings.
Line_iterator & Line_iterator::operator-(int n)
TCHAR & Line_iterator::operator*()
References pWChar.
Line_iterator & Line_iterator::operator=(const Line_iterator &m)
References nIndex, pBlock, pLine, pWChar.
bool Line_iterator::operator==(const Line_iterator &m)
References nIndex, pBlock.
bool Line_iterator::operator!=(const Line_iterator &m)