Cursor
Position Cursor::start
Referenced by Choose, Set_Height_Light, UserMessageProc.
Position Cursor::end
Referenced by Choose, Set_Height_Light, UserMessageProc.
CText* Cursor::pText
Referenced by Characters_before_Cursor, CharactersProperty_before_Cursor, Cursor, CursorLocation, CursorToPosition_After, isEnAfter, isLegalCursor, isTextTail, PositionToCursor, SethText.
int Cursor::nWidth
Referenced by Characters_before_Cursor, Cursor, CursorLocation, isLegalCursor, PositionToCursor, SetWidth.
int Cursor::nHeight
Referenced by Cursor, CursorToPosition, CursorToPosition_After, isTextTail, PositionToCursor, SetHeight.
bool Cursor::bChoose
Referenced by Choose, Cursor, isChoose, ResetChoose, SetChoose.
Cursor::Cursor(CText *p, int width, int height)
References bChoose, nHeight, nWidth, pText.
void Cursor::SethText(CText *p)
References pText.
Referenced by UserMessageProc.
void Cursor::SetWidth(int width)
References nWidth.
void Cursor::SetHeight(int height)
References nHeight.
bool Cursor::isEnBefore(int LineNumber, int x)
References CharactersProperty_before_Cursor.
bool Cursor::isEnAfter(int LineNumber, int x)
References Characters_before_Cursor, CursorLocation, CText::GetLinePointer, isLegalCursor, CText::Line_Size, pText.
Referenced by UserMessageProc.
bool Cursor::isLegalCursor(int LineNumber, int x)
References CText::GetLinePointer, CLine::Line_Width, nWidth, pText.
Referenced by Characters_before_Cursor, CharactersProperty_before_Cursor, CursorLocation, CursorToPosition, isEnAfter, UserMessageProc.
bool Cursor::isTextTail(int x, int y)
References CursorToPosition, CText::GetLinePointer, CText::Line_Number, CLine::nDataSize, nHeight, CLine::nLineNumber, pText, Position::Sequence.
int Cursor::Characters_before_Cursor(int LineNumber, int x)
References CursorLocation, CText::GetLinePointer, isLegalCursor, nWidth, pText.
Referenced by CharactersProperty_before_Cursor, CursorToPosition, isEnAfter, UserMessageProc.
int Cursor::CharactersProperty_before_Cursor(int LineNumber, int x)
References Characters_before_Cursor, CText::GetLinePointer, isLegalCursor, pText.
Referenced by isEnBefore, UserMessageProc.
int Cursor::CursorLocation(int LineNumber, int x)
References isLegalCursor, CText::Line_Width, nWidth, pText.
Referenced by Characters_before_Cursor, CursorToPosition, isEnAfter, UserMessageProc.
Position Cursor::CursorToPosition(int x, int y)
References Characters_before_Cursor, CursorLocation, isLegalCursor, nHeight.
Referenced by CursorToPosition_After, isTextTail, UserMessageProc.
Position Cursor::CursorToPosition_After(int x, int y)
References CursorToPosition, CText::GetLinePointer, CText::Line_Number, CLine::nDataSize, nHeight, CLine::nLineNumber, CLine::pNextLine, pText, Position::Sequence.
Referenced by UserMessageProc.
POINT Cursor::PositionToCursor(Position position)
References CText::Line_Width, Position::LineNumber, nHeight, nWidth, pText, Position::Sequence.
Referenced by UserMessageProc.
void Cursor::Choose(Position s, Position e)
References bChoose, end, start.
Referenced by UserMessageProc.
void Cursor::SetChoose()
References bChoose.
void Cursor::ResetChoose()
References bChoose.
Referenced by UserMessageProc.
bool Cursor::isChoose()
References bChoose.
Referenced by UserMessageProc.