editbox.h
MyTextOut
Referenced by PaintWindow.
HTEXT
Referenced by Find, MoveCaret, PaintWindow, WndProc.
TEXTSIZE
Referenced by Find, SelectTextSize, WndProc.
STARTPOS
Referenced by AdjustCaretPosBeforeBackspace, AdjustWindowPos, SelectHighlight, WndProc.
ENDPOS
Referenced by AdjustCaretPosBeforeBackspace, AdjustWindowPos, SelectHighlight, WndProc.
MEMDC
Referenced by PaintWindow, WndProc.
BITMAP
BRUSH
Referenced by DefaultFill, PaintWindow.
MTIMER
Referenced by WndProc.
STIMER
FONT
CARETPOS
Referenced by AdjustWindowPos, Find, MoveCaret, SelectCaretPos, SelectTitledWindow, SelectUntitledWindow, WndProc.
CHARSIZE
Referenced by AdjustWindowPos, DefaultFill, PaintWindow, SelectCaretPos, SelectHighlight, SelectTextSize, SelectWindowSize, WndProc.
CARETSIZE
Referenced by SelectUntitledWindow, WndProc.
WINDOWPOS
Referenced by AdjustWindowPos, PaintWindow, SelectCaretPos, SelectHighlight, SelectWindowPos, WndProc.
WINDOWSIZE
Referenced by AdjustWindowPos, PaintWindow, SelectHighlight, SelectTextSize, SelectTitledWindow, SelectWindowSize, WndProc.
PAGESIZE
Referenced by AdjustWindowPos, DefaultFill, SelectCaretPos, SelectWindowSize, WndProc.
INRANGEX
Referenced by AdjustWindowPos, SelectCaretPos, WndProc.
INRANGEY
Referenced by AdjustWindowPos, SelectCaretPos, WndProc.
ZHWIDTH
USWIDTH
Referenced by AdjustWindowPos, CreateUser, DefaultFill, PaintWindow, SelectCaretPos, SelectTextSize, SelectWindowSize, WndProc.
ZHHEIGHT
USHEIGHT
Referenced by AdjustWindowPos, CreateUser, DefaultFill, PaintWindow, SelectCaretPos, SelectHighlight, SelectTextSize, SelectWindowSize, WndProc.
AFTER_CARET
Referenced by Find.
BEFORE_CARET
Referenced by Find.
WHOLE_TEXT
Referenced by Find.
FIND
Referenced by Find, WndProc.
REPLACE
Referenced by Find, WndProc.
typedef struct _TIMER TIMER
typedef struct _TIMER * HTIMER
typedef CText* HTEXT
typedef CText * LPTEXT
typedef struct _TEXT_USER TEXTUSER
typedef struct _TEXT_USER * LPTEXTUSER
typedef struct _TEXT_USER * HTEXTUSER
typedef struct _TEXT_KERNEL TEXTKERNEL
typedef struct _TEXT_KERNEL * LPTEXTKERNEL
typedef struct _TEXT_KERNEL * HTEXTKERNEL
typedef struct _TEXT_GDI TEXTGDI
typedef struct _TEXT_GDI * LPTEXTGDI
typedef struct _TEXT_GDI * HTEXTGDI
typedef struct _TEXT_INFO TEXTINFO
typedef struct _TEXT_INFO * LPTEXTINFO
typedef struct _TEXT_INFO * HTEXTINFO
typedef RECT* LPRECT
HTIMER _stdcall CreateTimer(DWORD time_length)
Referenced by WndProc.
BOOL _stdcall KillTimer(HTIMER timer)
Referenced by WndProc.
BOOL IsTimerStopped(HTIMER hTimer)
References _TIMER::time_mutex.
Referenced by WndProc.
HTEXTUSER __stdcall CreateUser(HWND hWnd)
References _TEXT_USER::m_hFont, _TEXT_USER::m_pCaretPos, _TEXT_USER::m_pCaretSize, _TEXT_USER::m_pCharSize, _TEXT_USER::m_pPageSize, _TEXT_USER::m_pWindowPos, _TEXT_USER::m_pWindowSize, USHEIGHT, USWIDTH.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseUser(HWND hWnd, HTEXTUSER hUser)
Referenced by ReleaseTextInfo.
HTEXTKERNEL __stdcall CreateKernel(HWND hWnd, HTEXTUSER hUser)
References CreateText, _TEXT_KERNEL::m_hText, _TEXT_USER::m_pCharSize, _TEXT_KERNEL::m_pEndPos, _TEXT_KERNEL::m_pStartPos, _TEXT_KERNEL::m_pTextSize.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseKernel(HWND hWnd, HTEXTKERNEL hKernel)
Referenced by ReleaseTextInfo.
HTEXTGDI __stdcall CreateGDI(HWND hWnd, HTEXTUSER hUser)
References _TEXT_GDI::m_hBitmap, _TEXT_GDI::m_hBrush, _TEXT_USER::m_hFont, _TEXT_GDI::m_hMemDC, _TEXT_GDI::m_hMouseTimer, _TEXT_GDI::m_hSaveTimer, _TEXT_USER::m_pWindowSize.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseGDI(HWND hWnd, HTEXTGDI hGDI)
References _TEXT_GDI::m_hBitmap, _TEXT_GDI::m_hBrush, _TEXT_GDI::m_hMemDC.
Referenced by ReleaseTextInfo.
HTEXTINFO __stdcall CreateTextInfo(HWND hWnd)
References CreateGDI, CreateKernel, CreateUser, _TEXT_INFO::m_hGDI, _TEXT_INFO::m_hKernel, _TEXT_INFO::m_hUser, _TEXT_INFO::m_hWnd.
Referenced by WndProc.
BOOL __stdcall ReleaseTextInfo(HWND hWnd, HTEXTINFO hTextInfo)
References hTextInfo, _TEXT_INFO::m_hGDI, _TEXT_INFO::m_hKernel, _TEXT_INFO::m_hUser, ReleaseGDI, ReleaseKernel, ReleaseUser.
Referenced by WndProc.
BOOL WINAPI MyTextOutW(_In_ HDC hdc, _In_ int x, _In_ int y, _In_reads_(c) LPCWSTR lpString, _In_ int c, _In_ short s, _In_ short e, _In_ int width)
BOOL MyInvalidateRect(HWND, LONG, LONG, LONG, LONG)
Referenced by AdjustWindowPos, SelectHighlight, SelectTitledWindow, WndProc.
BOOL AdjustCaretPosBeforeBackspace(HWND, HTEXTINFO)
References ENDPOS, SelectHighlight, STARTPOS.
Referenced by WndProc.
BOOL AdjustWindowPos(HWND, HTEXTINFO)
References CARETPOS, CHARSIZE, DefaultFill, ENDPOS, INRANGEX, INRANGEY, MyInvalidateRect, MyScrollWindow, PAGESIZE, PRINTCARETPOS, PRINTENDL, PRINTPAGESIZE, PRINTWINDOWPOS, PRINTWINDOWSIZE, SelectWindowPos, STARTPOS, USHEIGHT, USWIDTH, WINDOWPOS, WINDOWSIZE.
Referenced by Find, MoveCaret, WndProc.
BOOL MoveCaret(HWND, UINT, HTEXTINFO)
References AdjustWindowPos, CARETPOS, HIDWORD, HTEXT, LODWORD, SelectCaretPos, SelectHighlight, UR_ERROR, UserMessageProc.
Referenced by WndProc.
BOOL SelectWindowPos(HTEXTINFO, POINT)
References WINDOWPOS.
Referenced by AdjustWindowPos, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectWindowSize(HTEXTINFO hTextInfo, LPRECT lpRect)
References CHARSIZE, _TEXT_INFO::m_hWnd, PAGESIZE, USHEIGHT, USWIDTH, WINDOWSIZE.
Referenced by SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectCaretPos(HTEXTINFO, POINT)
References CARETPOS, CHARSIZE, INRANGEX, INRANGEY, _TEXT_INFO::m_hWnd, PAGESIZE, USHEIGHT, USWIDTH, WINDOWPOS.
Referenced by Find, MoveCaret, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectHighlight(HTEXTINFO, POINT, POINT)
References CHARSIZE, ENDPOS, _TEXT_INFO::m_hWnd, MyInvalidateRect, STARTPOS, USHEIGHT, WINDOWPOS, WINDOWSIZE.
Referenced by AdjustCaretPosBeforeBackspace, Find, MoveCaret, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectTextSize(HTEXTINFO, POINT)
References CHARSIZE, _TEXT_INFO::m_hWnd, TEXTSIZE, USHEIGHT, USWIDTH, WINDOWSIZE.
Referenced by Find, SelectUntitledWindow, WndProc.
BOOL SelectUntitledWindow(HWND, HTEXTINFO)
References CARETPOS, CARETSIZE, SelectCaretPos, SelectHighlight, SelectTextSize, SelectWindowPos, SelectWindowSize.
Referenced by WndProc.
BOOL SelectTitledWindow(HWND, HTEXTINFO, POINT, LPCWSTR)
References CARETPOS, MyInvalidateRect, SelectCaretPos, SelectHighlight, SelectWindowPos, SelectWindowSize, WINDOWSIZE.
Referenced by WndProc.
BOOL MyScrollWindow(HWND, int, int)
Referenced by AdjustWindowPos, WndProc.
BOOL DefaultFill(HWND, HTEXTINFO)
References BRUSH, CHARSIZE, PAGESIZE, USHEIGHT, USWIDTH.
Referenced by AdjustWindowPos, WndProc.
BOOL PaintWindow(LPPAINTSTRUCT, HTEXTINFO)
References BRUSH, CHARSIZE, HIDWORD, HTEXT, LODWORD, MEMDC, MyTextOut, UM_TEXT, UR_ERROR, UserMessageProc, USHEIGHT, USWIDTH, WINDOWPOS, WINDOWSIZE.
Referenced by WndProc.
BOOL operator==(POINT left, POINT right)