textoperation.cpp
BOOL MyInvalidateRect(HWND hWnd, LONG left, LONG right, LONG top, LONG bottom)
Referenced by AdjustWindowPos, SelectHighlight, SelectTitledWindow, WndProc.
BOOL operator==(POINT left, POINT right)
BOOL AdjustCaretPosBeforeBackspace(HWND hWnd, HTEXTINFO hTextInfo)
References ENDPOS, SelectHighlight, STARTPOS.
Referenced by WndProc.
BOOL AdjustWindowPos(HWND hWnd, HTEXTINFO hTextInfo)
References CARETPOS, CHARSIZE, DefaultFill, ENDPOS, INRANGEX, INRANGEY, MyInvalidateRect, MyScrollWindow, PAGESIZE, PRINTCARETPOS, PRINTENDL, PRINTPAGESIZE, PRINTWINDOWPOS, PRINTWINDOWSIZE, SelectWindowPos, STARTPOS, USHEIGHT, USWIDTH, WINDOWPOS, WINDOWSIZE.
Referenced by Find, MoveCaret, WndProc.
BOOL MoveCaret(HWND hWnd, UINT message, HTEXTINFO hTextInfo)
References AdjustWindowPos, CARETPOS, HIDWORD, HTEXT, LODWORD, SelectCaretPos, SelectHighlight, UR_ERROR, UserMessageProc.
Referenced by WndProc.
BOOL SelectWindowPos(HTEXTINFO hTextInfo, POINT thePos)
References WINDOWPOS.
Referenced by AdjustWindowPos, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectWindowSize(HTEXTINFO hTextInfo, LPRECT lpRect)
References CHARSIZE, _TEXT_INFO::m_hWnd, PAGESIZE, USHEIGHT, USWIDTH, WINDOWSIZE.
Referenced by SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectCaretPos(HTEXTINFO hTextInfo, POINT thePos)
References CARETPOS, CHARSIZE, INRANGEX, INRANGEY, _TEXT_INFO::m_hWnd, PAGESIZE, USHEIGHT, USWIDTH, WINDOWPOS.
Referenced by Find, MoveCaret, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectHighlight(HTEXTINFO hTextInfo, POINT theStart, POINT theEnd)
References CHARSIZE, ENDPOS, _TEXT_INFO::m_hWnd, MyInvalidateRect, STARTPOS, USHEIGHT, WINDOWPOS, WINDOWSIZE.
Referenced by AdjustCaretPosBeforeBackspace, Find, MoveCaret, SelectTitledWindow, SelectUntitledWindow, WndProc.
BOOL SelectTextSize(HTEXTINFO hTextInfo, POINT theSize)
References CHARSIZE, _TEXT_INFO::m_hWnd, TEXTSIZE, USHEIGHT, USWIDTH, WINDOWSIZE.
Referenced by Find, SelectUntitledWindow, WndProc.
BOOL SelectUntitledWindow(HWND hWnd, HTEXTINFO hTextInfo)
References CARETPOS, CARETSIZE, SelectCaretPos, SelectHighlight, SelectTextSize, SelectWindowPos, SelectWindowSize.
Referenced by WndProc.
BOOL SelectTitledWindow(HWND hWnd, HTEXTINFO hTextInfo, POINT pTextSize, LPCWSTR lpszFileName)
References CARETPOS, MyInvalidateRect, SelectCaretPos, SelectHighlight, SelectWindowPos, SelectWindowSize, WINDOWSIZE.
Referenced by WndProc.
BOOL MyScrollWindow(HWND hWnd, int xOffset, int yOffset)
Referenced by AdjustWindowPos, WndProc.
BOOL DefaultFill(HWND hWnd, HTEXTINFO hTextInfo)
References BRUSH, CHARSIZE, PAGESIZE, USHEIGHT, USWIDTH.
Referenced by AdjustWindowPos, WndProc.
BOOL PaintWindow(LPPAINTSTRUCT lpPaint, HTEXTINFO hTextInfo)
References BRUSH, CHARSIZE, HIDWORD, HTEXT, LODWORD, MEMDC, MyTextOut, UM_TEXT, UR_ERROR, UserMessageProc, USHEIGHT, USWIDTH, WINDOWPOS, WINDOWSIZE.
Referenced by WndProc.