Record
Position Record::start
Referenced by Clear_Choose_Data, ReDo, Save_Delete_Data, Save_Merge_Line_Data, Set_Choose_Data, UserMessageProc.
Position Record::end
Referenced by Clear_Choose_Data, ReDo, Save_Merge_Line_Data, Set_Choose_Data, UserMessageProc.
CText* Record::pText
Referenced by Record, ReDo, Save_Delete_Data, ~Record.
UINT Record::ACT
Referenced by Record, ReDo, UserMessageProc.
std::wstring Record::Deleted_Data
Referenced by ReDo, Save_Delete_Data.
Record::Record(UINT flag)
References ACT, pText.
Record::~Record()
References pText.
void Record::ReDo(CText *p)
References ACT, CText::Delete, Deleted_Data, CText::DeleteLines, end, CText::EnterNewLine, CText::GetLinePointer, CText::Insert, CLine::InsertStrings, Position::LineNumber, CLine::nDataSize, CLine::pNextLine, pText, RD_DELETE, RD_INSERT, RD_MERGE_LINE, RD_RETURN, Position::Sequence, start, CLine::TransformToWString.
Referenced by UserMessageProc.
void Record::Save_Delete_Data(CText *pc, Position first, Position last)
References CText::Copy, Deleted_Data, pText, Position::Sequence, start.
Referenced by UserMessageProc.
void Record::Save_Merge_Line_Data(CText *p, int LineNumber)
References end, CText::GetLinePointer, CLine::nDataSize, start.
Referenced by UserMessageProc.
void Record::Set_Choose_Data(Position first, Position last)
References end, start.
Referenced by UserMessageProc.
void Record::Clear_Choose_Data()
References end, Position::LineNumber, Position::Sequence, start.