textinfo.cpp
HTEXTINFO __stdcall CreateTextInfo(HWND hWnd)
References CreateGDI, CreateKernel, CreateUser, _TEXT_INFO::m_hGDI, _TEXT_INFO::m_hKernel, _TEXT_INFO::m_hUser, _TEXT_INFO::m_hWnd.
Referenced by WndProc.
BOOL __stdcall ReleaseTextInfo(HWND hWnd, HTEXTINFO hTextInfo)
References hTextInfo, _TEXT_INFO::m_hGDI, _TEXT_INFO::m_hKernel, _TEXT_INFO::m_hUser, ReleaseGDI, ReleaseKernel, ReleaseUser.
Referenced by WndProc.
HTEXTUSER __stdcall CreateUser(HWND hWnd)
References _TEXT_USER::m_hFont, _TEXT_USER::m_pCaretPos, _TEXT_USER::m_pCaretSize, _TEXT_USER::m_pCharSize, _TEXT_USER::m_pPageSize, _TEXT_USER::m_pWindowPos, _TEXT_USER::m_pWindowSize, USHEIGHT, USWIDTH.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseUser(HWND hWnd, HTEXTUSER hUser)
Referenced by ReleaseTextInfo.
HTEXTKERNEL __stdcall CreateKernel(HWND hWnd, HTEXTUSER hUser)
References CreateText, _TEXT_KERNEL::m_hText, _TEXT_USER::m_pCharSize, _TEXT_KERNEL::m_pEndPos, _TEXT_KERNEL::m_pStartPos, _TEXT_KERNEL::m_pTextSize.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseKernel(HWND hWnd, HTEXTKERNEL hKernel)
Referenced by ReleaseTextInfo.
HTEXTGDI __stdcall CreateGDI(HWND hWnd, HTEXTUSER hUser)
References _TEXT_GDI::m_hBitmap, _TEXT_GDI::m_hBrush, _TEXT_USER::m_hFont, _TEXT_GDI::m_hMemDC, _TEXT_GDI::m_hMouseTimer, _TEXT_GDI::m_hSaveTimer, _TEXT_USER::m_pWindowSize.
Referenced by CreateTextInfo.
BOOL __stdcall ReleaseGDI(HWND hWnd, HTEXTGDI hGDI)
References _TEXT_GDI::m_hBitmap, _TEXT_GDI::m_hBrush, _TEXT_GDI::m_hMemDC.
Referenced by ReleaseTextInfo.