timer.cpp
static DWORD __stdcall RunTimer(LPVOID lpVoid)
References _TIMER::time_mutex, _TIMER::time_rest.
Referenced by _TIMER::_TIMER.
BOOL IsTimerStopped(HTIMER hTimer)
References _TIMER::time_mutex.
Referenced by WndProc.
HTIMER _stdcall CreateTimer(DWORD time_length)
Referenced by WndProc.
BOOL _stdcall KillTimer(HTIMER timer)
Referenced by WndProc.